name: wine-platform-7-stable-core22
adopt-info: wine
summary: wine platform snap it provides stable WINE 7 for snaps
description: |
 This snap creates a WINE stable 7 via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22
compression: lzo

slots:
  wine-7-stable-c22:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-stable

parts:
  wine:
    plugin: nil
    build-packages:
      - dpkg
      - wget
    override-build: |
      snapcraftctl build

      ARCH="$(dpkg --print-architecture)"
      WINE_VER="7.0.2"

      # set snap version
      snapcraftctl set-version "$WINE_VER"

      # wget and dpkg extract the wine debs
      ## supporting binaries which are arch-specific but the same filenames in both architectures so we only install the native architecture
      DEB_URLS="https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-${ARCH}/wine-stable_${WINE_VER}~jammy-1_${ARCH}.deb"

      ## wine loaders - this one is the native system architecture
      DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-${ARCH}/wine-stable-${ARCH}_${WINE_VER}~jammy-1_${ARCH}.deb"

      if [ "$ARCH" = "amd64" ]; then
        ## on amd64 builds we need to also bundle the i386 wine loaders
        DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-i386/wine-stable-i386_${WINE_VER}~jammy-1_i386.deb"
      fi

      for DEB_URL in ${DEB_URLS}; do
        DEB=$(basename "${DEB_URL}")
        echo "Downloading ${DEB_URL}..."
        wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
        echo "Unpacking ${DEB}..."
        dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
        rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      done

      # Cleanup
      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt/wine-stable/share/applications
      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt/wine-stable/share/man
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr

      # Disable winemenubuilder
      sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' "${SNAPCRAFT_PART_INSTALL}"/opt/wine-stable/share/wine/wine.inf
